# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dab39ef98b20b87a459a989483f516672d134aeba5d40cbe52c0a12b89cbba26893db66813dc117262e48f9265c1e81bc7ca644c22fbfad2b07325e99f5f6c5

test:
  secret_key_base: 7fb01507141f2a13c15f72ea6ecbace2b33ed1980a3cc49d37607fb7fb6bbe8f98f4aee8d875e9bf827f5f7031ebc19fcc8a46e4dfa470ff3eb1fd2205573afe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
